spring.application.name=taller-reparacion

spring.datasource.url=jdbc:mysql://localhost:3306/taller_reparacion?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.config.import=optional:classpath:application-local.properties
spring.datasource.username=root
spring.datasource.password=AutoCore2026

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
